### ISSUE TITLE
Error when attempting to search for an address

### ISSUE THREAD

**Issue by pRizz** [lsquires/open-iota#4]
When searching for an address, the webapp goes through a sequence of network calls. One of them is `getInclusionStates`. For some reason, sometimes, but not always, I get this as the response 
```
{"error":"This operations cannot be executed: The subtangle has not been updated yet.","duration":19}
```
using my donation address as an example:
https://open-iota.prizziota.com/#/search/address/ARDPDHLZPQZRDBPKTZBIK9OFKCJMGCHFQJTQEXL9KRIVSHNRGHJCEOCMRFXGJMQXDVGNFTTS9GUIOJXXW9RONFYJKW

**Comment by lsquires** [comment]
I saw it wasn't working, but now the request goes through without error, I suppose it was a problem with the node somehow?

**Comment by pRizz** [comment]
I agree, I think it is the node, but perhaps we can add a retry and timer of some sort to mitigate this error until the node is fixed.

**Comment by pRizz** [comment]
This error just means the node was probably restarted recently and hasn't built up its db in memory yet, or something similar.
