### ISSUE TITLE
Have you considered using the MIT License?

### ISSUE THREAD

**Issue by pRizz** [lsquires/open-iota#6]
I want to utilize some snippets of code from this project in another project, but the GPL license adds some complications. To make this simpler, would you consider changing this to the MIT License, which is more permissive? I would still attribute the snippets to you and your project :)

Edit: My main issue with GPL is that it forces any software that contains it to also become GPL licesnsed, which I think is unreasonable. MIT is more permissive about this. https://www.patrick-wied.at/blog/how-to-correctly-use-code-you-didnt-write

**Comment by pRizz** [comment]
If this is not changed, then I will have to reimplement the code, just fyi.

**Comment by lsquires** [comment]
I'm changing it now, thanks for letting me know!

**Comment by pRizz** [comment]
@lsquires :tada: Thank you! Sorry if I sounded aggressive.
